### ISSUE TITLE
cannot append list args to default_config_files

### ISSUE THREAD

**Issue by tshu-w** [omni-us/jsonargparse#157]
## 🐛 Bug report

cannot append list args to default_config_files

### To reproduce

```python
from jsonargparse import CLI

def test_fn(
    nums: list[int] = [0],
    strs: list[str] = ["a"],
):
    pass

if __name__ == "__main__":
    CLI(test_fn, default_config_files=["config.yaml"])
```
```yaml
nums:
- 1
strs:
- x
```
```console
$ python test.py --nums+ 2 --print_config
nums:
- 2
strs:
- x
```

### Expected behavior

`python test.py --nums+ 2 --print_config` got
```yaml
nums:
- 1
- 2
strs:
- x
```

### Environment

- jsonargparse version: 4.13.2
- Python version: 3.9.12
- How jsonargparse was installed: `pip install jsonargparse`
- OS: Linux

**Comment by mauvilsa** [comment]
This has been fixed in commit https://github.com/omni-us/jsonargparse/commit/363e05d84e05db88201c96ebba7a442c57b6dac1 and included in v4.13.3 just released.

**Comment by tshu-w** [comment]
Dear @mauvilsa, I found this issue still happened with subcommand:
Here is a example:
```python
from jsonargparse import CLI

def test_fn(
    nums: list[int] = [0],
    strs: list[str] = ["a"],
):
    pass

def empty_fn(
):
    pass

if __name__ == "__main__":
    CLI([test_fn, empty_fn], default_config_files=["config.yaml"])
```
```yaml
test_fn:
  nums:
  - 1
  strs:
  - x
```
```console
λ python test.py test_fn --nums+ 2 --print_config
nums:
- 2
strs:
- x
```

**Comment by mauvilsa** [comment]
I pushed a fix for the subcommands in commit https://github.com/omni-us/jsonargparse/commit/03fed89c4101fa1a2a7ccba027b99bc1a25d4922.

**Comment by tshu-w** [comment]
Thanks, @mauvilsa ! It works now.
