### ISSUE TITLE
Config check failed with `add_subclass_arguments(required=False)`

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#83]
```python
from jsonargparse import ArgumentParser

class A:
    ...

class B:
    ...

parser = ArgumentParser()
parser.add_subclass_arguments((A, B), nested_key="foo", required=False)
args = parser.parse_args()
```
produces:
```
scratch_12.py: error: Configuration check failed :: Parser key "foo": Value {} does not validate against any of the types in typing.Union[__main__.A, __main__.B]:
  - Type <class '__main__.A'> expects an str or a Dict with a class_path entry but got "{}"
  - Type <class '__main__.B'> expects an str or a Dict with a class_path entry but got "{}"
```

My assumption was that by setting `required=False`, `--foo` does not need to be passed.
And `args` would be an empty dictionary.

**Comment by mauvilsa** [comment]
Fixed in v3.19.2

**Comment by carmocca** [comment]
@mauvilsa If I add the following line at the end of the snippet above, the error still appears:

`args_init = parser.instantiate_classes(args)`

Can you re-open this?

**Comment by carmocca** [comment]
Looking at the commit that closed this PR, I'd say that the assertion should be changed to `self.assertEqual(cfg, {})`
